################################################################################
## ENTRY POINT, it's a nginx which proxies to other internal services ##########
################################################################################
proxy:
  image: docker-registry.eyeosbcn.com/eyeos-proxy:latest
  net: "host"
  dns: "127.0.0.1"
  privileged: true
  environment:
    - EYEOS_DEVELOPMENT_MODE=false


################################################################################
# DESKTOP ######################################################################
################################################################################
applications:
  image: docker-registry.eyeosbcn.com/eyeos-application:latest
  net: "host"
  dns: "127.0.0.1"
  environment:
      - EYEOS_DEVELOPMENT_MODE=false

################################################################################
## SYSTEM DEPENDENCIES #########################################################
################################################################################
mongodb:
  image: mongo:2.6
  net: "host"
  dns: "127.0.0.1"
  environment:
      - EYEOS_DEVELOPMENT_MODE=false

################################################################################
## BUS TO HTTP #################################################################
################################################################################
httpToBus:
  image: docker-registry.eyeosbcn.com/eyeos-httptobusserver:latest
  net: "host"
  privileged: true
  dns: "127.0.0.1"
  environment:
      - EYEOS_DEVELOPMENT_MODE=false

################################################################################
## OTHER SERVICES ##############################################################
################################################################################

rabbitmq:
  image: docker-registry.eyeosbcn.com/docker-rabbitmq:latest
  net: "host"
  dns: "127.0.0.1"
  environment:
      - EYEOS_DEVELOPMENT_MODE=false
